<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModulSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('app_moduls')->insert([
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Login',
                'modul_description' => 'Login HRIS 3',
                'modul_status' => 'On Progress',
                'application_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Master',
                'modul_description' => 'Master HRIS 3',
                'modul_status' => 'Active',
                'application_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Calon Karyawan KX',
                'modul_description' => 'Calon Karyawan KX HRIS 3',
                'modul_status' => 'Active',
                'application_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Calon Karyawan MNJ',
                'modul_description' => 'Calon Karyawan MNJ HRIS 3',
                'modul_status' => 'Active',
                'application_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Data Karyawan',
                'modul_description' => 'Data Karyawan HRIS 3',
                'modul_status' => 'Active',
                'application_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Absensi dan Cuti',
                'modul_description' => 'Absensi dan Cuti HRIS 3',
                'modul_status' => 'Active',
                'application_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'PPK',
                'modul_description' => 'PPK HRIS 3',
                'modul_status' => 'Active',
                'application_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Gaji Bulanan',
                'modul_description' => 'Gaji Bulanan HRIS 3',
                'modul_status' => 'Active',
                'application_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Gaji Harian dan Borongan',
                'modul_description' => 'Gaji Harian dan Borongan HRIS 3',
                'modul_status' => 'Active',
                'application_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'E-Payroll',
                'modul_description' => 'E-Payroll HRIS 3',
                'modul_status' => 'Active',
                'application_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Transfer',
                'modul_description' => 'Transfer HRIS 3',
                'modul_status' => 'Active',
                'application_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HRIS 2
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Login',
                'modul_description' => 'Login HRIS 2',
                'modul_status' => 'Active',
                'application_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Master',
                'modul_description' => 'Master HRIS 2',
                'modul_status' => 'Active',
                'application_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Absensi dan Cuti',
                'modul_description' => 'Absensi dan Cuti HRIS 2',
                'modul_status' => 'Active',
                'application_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Display Karyawan',
                'modul_description' => 'Display Karyawan HRIS 2',
                'modul_status' => 'Active',
                'application_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Display Karyawan (All)',
                'modul_description' => 'Display Karyawan (All) HRIS 2',
                'modul_status' => 'Active',
                'application_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Data Karyawan',
                'modul_description' => 'Data Karyawan HRIS 2',
                'modul_status' => 'Active',
                'application_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Rekrutmen',
                'modul_description' => 'Rekrutmen HRIS 2',
                'modul_status' => 'Active',
                'application_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Pengembangan SDM',
                'modul_description' => 'Pengembangan SDM HRIS 2',
                'modul_status' => 'Active',
                'application_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Kompetensi',
                'modul_description' => 'Kompetensi HRIS 2',
                'modul_status' => 'Active',
                'application_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Medical Record',
                'modul_description' => 'Medical Record HRIS 2',
                'modul_status' => 'Active',
                'application_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Pembinaan',
                'modul_description' => 'Pembinaan HRIS 2',
                'modul_status' => 'Active',
                'application_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // KPI (Key Performance Indicator)
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Dashboard',
                'modul_description' => 'Dashboard KPI',
                'modul_status' => 'Active',
                'application_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Master',
                'modul_description' => 'Master KPI',
                'modul_status' => 'Active',
                'application_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Parameter',
                'modul_description' => 'Parameter KPI',
                'modul_status' => 'Active',
                'application_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Penilaian KPI',
                'modul_description' => 'Penilaian KPI',
                'modul_status' => 'Active',
                'application_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'Setting',
                'modul_description' => 'Setting KPI',
                'modul_status' => 'Active',
                'application_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //ESS (Employee Self Service)
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'ESS',
                'modul_description' => 'ESS (Employee Self Service)',
                'modul_status' => 'Active',
                'application_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //E-Recruitment
            [
                'modul_key' => Str::uuid(),
                'modul_name' => 'E-Rectruitment',
                'modul_description' => 'E-Recruitment',
                'modul_status' => 'Active',
                'application_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
